### ISSUE TITLE
is empty validate

### ISSUE THREAD

**Issue by iamjonathankush** [xorock/zend-service-recaptcha-v2#1]
when i validate the form it says that the recaptcha has a error of isempty. i clicked the checkbox for the recapcha

**Comment by xorock** [comment]
Could You please provide a code for this error scenario? What template engine do You use?

**Comment by iamjonathankush** [comment]
in the form (sorry dont know how to format code in github):

`       $this->add([
		        		'type'       => Captcha::class,
		        		'name'       => 'recaptcha', // name is required for element to be validated
		        		'options'    => [
		        				'label' => 'Please answer question',
		        				'captcha' => [
		        						'class' => ReCaptcha2::class,
		        						'options' => [
		        								'hl' => Pluto::registry('lang'), // english is set by deafult, this line is not required
		        								'theme' => 'light', // see options below
		        								'callback' => '', // callback function, etc.
		        								'public_key'  => Pluto::registry('googapi_recaptcha_public_key'),
		        								'private_key' => Pluto::registry('googapi_recaptcha_private_key')
		        						],
		        				],
		        		],
		        ]);`

and then in the phtml file

`<?= $this->formElement($form->get('recaptcha')); ?>`

**Comment by iamjonathankush** [comment]
Here is the form messages when i process the form using this code:

`public function contactAction()
    {
    	$form = new ContactForm();
    	if($this->getRequest()->isPost()) {
    		$data = $this->params()->fromPost();    		
    		$form->setData($data);
    		if ($form->isValid()) {
    			echo 1;die();
    		} else {
    			Pluto::dump($form->getMessages());
    		}
    	}
    	return new ViewModel(['contactform'=>$form]);
    }`

 array(1) {
  ["recaptcha"] => array(1) {
    ["isEmpty"] => string(36) "Value is required and can't be empty"
  }
}

**Comment by xorock** [comment]
Default POST parameter for ReCaptcha element is 'g-recaptcha-response' as in https://developers.google.com/recaptcha/docs/verify and that is what service expects. You've changed it to 'recaptcha'. I have to keep this name because element or service could be instantiated in many different ways.

Alternatively, You can use ReCaptcha2 form element and skip this part (see docs).

```php
use ZfServiceReCaptcha2\Form\Element\ReCaptcha2;

$this->add([
    'type'       => ReCaptcha2::class,
    'options'    => [
        'label' => 'Please answer question',
    ],
]);
```

and then copy `zend-service-recaptcha-v2/config/autoload/recaptcha.global.php.dist` file to Your autoloaded configuration files.

Let me know if it helps.

**Comment by iamjonathankush** [comment]
thanks .works perfectly
